### ISSUE TITLE
Metal support on iOS

### ISSUE THREAD

**Issue by marczellm** [googlevr/cardboard#11]
OpenGL is deprecated on iOS, please provide support for Metal based rendering in this SDK.

**Comment by jballoffet** [comment]
Thanks for requesting the feature, adding Metal support is on our roadmap. Please star or watch this issue to be notified when it becomes available.

**Comment by googelybear** [comment]
@jballoffet do you have a rough timeline when it will be available? We're starting a new development and want to prevent developing something with a framework that's already deprecated and 2 months later re-write everything. Thanks in advance.

**Comment by jballoffet** [comment]
We hope to release Metal support later this year, before iOS development requires it. Please star or watch this issue to be notified when it becomes available.

**Comment by julien-tamade** [comment]
Any update on this?

**Comment by julien-tamade** [comment]
@jballoffet Any chance you could give an update on the expected timeline for this? I'd love to have something I can take back to my team because our app sometimes crashes due to GLES2 and I want to see when metal support will be available.

**Comment by ZucchiniFred** [comment]
Hi this seems like a really important issue. Would be great to get a sense of how progress is going on this front and when we can expect metal support. My app is heavily reliant on the cardboard plugin and we've noticed some instability issues probably similar to what @julien-tamade mentioned due to GLES2. Even if you've made 0 progress that would be good to know as well.

**Comment by andyz** [comment]
Indeed Metal & OpenGL ES 3 are very important, I doubt any non-ancient android or iOS phones need only ogl2, nor would it be recommended not to use metal on iOS (so deprecated in Unity LTS)
Curious on reasons for not having support yet, Google not allowing the time/resources?

**Comment by JoaoBorks** [comment]
Not having Metal support blocks the usage of **ARKit** for whoever wants to create AR experiences as well.

**Comment by andyz** [comment]
In fact I can not use this as opengl es 2 in Unity 2019 breaks a lot of materials with silly things like wrapping not working on texturing

**Comment by jballoffet** [comment]
Thank you for your patience. Adding Metal support is still on our roadmap for the current year. We prioritized OpenGLES 2.0 first as it is required to support all Android phones (see the [distribution dashboard](https://developer.android.com/about/dashboards#OpenGL). OpenGLES 2.0 is still supported on iOS 14 from our tests. We will update this once Metal support is available.

**Comment by julien-tamade** [comment]
@jballoffet do you have an idea of timeline for metal? Thanks!

**Comment by andyz** [comment]
> Thank you for your patience. Adding Metal support is still on our roadmap for the current year. We prioritized OpenGLES 2.0 first as it is required to support all Android phones (see the [distribution dashboard](https://developer.android.com/about/dashboards#OpenGL). OpenGLES 2.0 is still supported on iOS 14 from our tests. We will update this once Metal support is available.

Sorry but that distribution board does not reflect development with Unity (which is most ? mobile games), and the small number with ogl 2 phones probably do not run VR.
Our Unity project does not render materials properly with the deprecated (by Unity) openGLES 2.0
Any way I hope for your fix soon

**Comment by ImmotionPeterL** [comment]
@jballoffet 
> we're focused on Metal support right now.

Is there an ETA on Metal support? We need to decide how we're going to move forward with our project now, and the wait for Metal support is the biggest deciding factor.

**Comment by jballoffet** [comment]
Adding Metal support is currently the highest priority, it is under active development and will be included in the next release of the Cardboard SDK (v1.5.0). You can also find this information in the [project dashboard](https://github.com/googlevr/cardboard/projects/1). We will update this issue once Metal support is available.

**Comment by Jeunyoung** [comment]
When is the next release version 1.5.0 that include Metal support on iOS?

**Comment by jballoffet** [comment]
A new release of the Cardboard SDK (including Metal support on iOS) is nearing completion and is currently working through the QA process. If all goes as planned, we hope to be able to ship the release soon.

Thank you for your excitement and your continued patience.

**Comment by xiesi88** [comment]
> A new release of the Cardboard SDK (including Metal support on iOS) is nearing completion and is currently working through the QA process. If all goes as planned, we hope to be able to ship the release soon.
> 
> Thank you for your excitement and your continued patience.

We really can't wait any longer. Our product needs the support of version 1.5.

**Comment by chaosemer** [comment]
This was fixed in v1.5.0.

**Comment by guneyozsan** [comment]
@chaosemer Referring to release notes of `v1.5.0`, `Unity bug #1329845: Metal support does not work on Unity 2019.3 or 2019.4.` The referenced Unity issue link now says `this is fixed in Version 2019.4.27f1`.

Are there any updates on Metal support on Unity 2019.4.27f1 and later with cardboard v1.5.0 or v1.6.0? Or, do we need to upgrade to unity 2020 LTS?

Asking because when we try `v1.6.0` with 2019.4.27f1 or 2019.4.28f1, we get certain flickering when switching to VR mode after migrating from OpenGLES to Metal. If we stay with OpenGLES we have random crashes or black screen freezes when returning from VR mode to normal mode.

Actually, we are stuck in between Metal and OpenGLES.

**Comment by julien-tamade** [comment]
+1 on this. Not ready to upgrade to 2020 yet but would love the metal support as we get crashes on startup and sometimes black screen as well

**Comment by guneyozsan** [comment]
@chaosemer We updated our app to Unity 2020.3.14f1 and we still have the flicker on iOS (So ours is not a Metal and Unity 2019 issue but a Metal issue in general). It looks like our second UI camera with a different depth is the cause of the flicker. I'll open a separate issue after some more testing.

**Comment by jballoffet** [comment]
Thanks for reaching out. As stated on the Unity issue, the XR + Metal integration was fixed in Unity 2019.4.27f1 for Unity 2019.4.x versions (by the time Cardboard XR plugin + Metal was released, it was working properly on all Unity 2020.x versions). 

Before the fix was applied (e.g. using Unity 2019.4.26f1), only a black texture was rendered on the screen. @guneyozsan, this means that the flicker you're seeing is caused by a different issue. I've just seen you have created a new issue, I'll take a look at it and I'll reach you out. Thanks!

**Comment by guneyozsan** [comment]
@jballoffet yes, after further inspection we also think the flicker is caused by a different issue specific to the overlay camera used for displaying HUD. The details are in the new issue.

**Comment by julien-tamade** [comment]
@jballoffet I'm getting flickering using metal with 2019.4.30f1 and cardboard v1.8.

Seems like it's a rendering/material issue. doesn't happen with GLE2. Any ideas?

https://user-images.githubusercontent.com/44389340/133529520-2d547588-1ea4-499e-bb1b-cdf1d5b8b27f.MP4

**Comment by guneyozsan** [comment]
Sorry I forgot to mention the issue on flicker: https://github.com/googlevr/cardboard/issues/286
@julien-tamade
