### ISSUE TITLE
Incorrect screen size and placement, and right and left eye looking away from each other on Android and iOS

### ISSUE THREAD

**Issue by guneyozsan** [googlevr/cardboard#168]
UPDATE 3: See https://github.com/googlevr/cardboard/issues/168#issuecomment-738856799 for the cause and resolution.

UPDATE 2: Also same on iOS.

UPDATE 1: Pixel 2 on Android 11 has the same problem (video capture in comment below). Also Samsung S7 mentioned runs on Android 8.

We just updated from GVR to Cardboard SDK v1.3.0. Along with a forced update from 2018 LTS to 2019.4.15f1 (it is the same in 2020.4.15f1 as well).

Our UI is 2D non-VR and we activate VR mode manually with a separate scene for VR.

When running on Samsung S7:
- The image is misaligned and incorrectly cropped.
- Left and right eye focus is incorrect (looking away from each other).
- Horizon is correct for right-eye but tilted for left-eye.
- Some distant objects in left-side of right eye are clipped, but objects in right-side of right eye are not. Left eye has no crop in visible area but may have some in non-visible area. (Perhaps the app thinks they are also non-visible to right eye).
![image](https://user-images.githubusercontent.com/19275187/100464554-e4892c00-30de-11eb-89de-aa970398787f.png)

I'll update when we have chance to test with other Android phones.

**Comment by jballoffet** [comment]
Thanks for reporting this issue. In order to allow us to reproduce it, could you please provide a link to a simple Unity project where this issue is depicted? Please also provide:
- The required steps to expose the issue.
- The viewer’s parameters being used.

**Comment by guneyozsan** [comment]
Update: Same in Pixel 2 on Android 11. This time with a video that shows the effects of clipping:
[20201201_085622_edited.zip](https://github.com/googlevr/cardboard/files/5630211/20201201_085622_edited.zip)

I'll try to create a repro project, but we have a high priority to achieve a working version for iOS. Our current users gradually become unable to use our app as more devices update to iOS 14.

**Comment by guneyozsan** [comment]
I discovered that the issue was due to timing of `Screen.orientation = ScreenOrientation.LandscapeLeft` when switching from our 2D scene (portrait) to VR scene (portrait). If you don't wait for it you get the broken view in the issue description.

Apparently it needs to wait to make sure transition is completed. Here is the code that initializes the VR scene:

`

    private void Awake()
    {
        Screen.orientation = ScreenOrientation.LandscapeLeft;
        StartCoroutine(StartXRWhenTransitionToLandscapeLeftIsComplete());
    }

    private IEnumerator StartXRWhenTransitionToLandscapeLeftIsComplete()
    {
        while (Screen.width < Screen.height)
        {
            // Screen orientation is still portrait.
            yield return null;
        }
        
        // Screen orientation is horizontal.
        StartCoroutine(XRManager.StartXR());
    }
`

**Comment by guneyozsan** [comment]
Here are the repro projects, working and not-working:

Here are some cases that did not work:
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/view-buggy-after-switching-to-vr-1
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/view-buggy-after-switching-to-vr-2
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/view-buggy-after-switching-to-vr-3
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/view-buggy-after-switching-to-vr-4
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/view-buggy-after-switching-to-vr-5

Versions with the fix, one switches to VR in previous scene, the other one switches to VR at the beginning of the VR scene:
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/view-NOT-buggy-after-switching-to-vr-1
https://github.com/guneyozsan/UnityGoogleCardboardTest/tree/view-NOT-buggy-after-switching-to-vr-2

Downloadable samples from the same repo as a reference:
[view-buggy-after-switching-to-vr-2.zip](https://github.com/googlevr/cardboard/files/5646783/view-buggy-after-switching-to-vr-2.zip)
[view-NOT-buggy-after-switching-to-vr-2.zip](https://github.com/googlevr/cardboard/files/5646784/view-NOT-buggy-after-switching-to-vr-2.zip)

**Comment by jballoffet** [comment]
Thanks for writing down all the resolution details. I'm closing this issue as it solved now.

**Comment by jeff-rey-unity** [comment]
I'm not getting the cross eyed, or the orientation issue, but I do have the clipping in the right eye on the left side of the screen.  My android one plus 6t does not have this issue, but my iphone 6s does.  Has anyone had this problem as stated above?  It almost looks like an occlusion culling problem in the right eye only, but even without baked data, I still have this issue.
