### ISSUE TITLE
[Unity] VR Content gets shifted to one half of the screen and the other half remains black

### ISSUE THREAD

**Issue by knightcube** [googlevr/cardboard#285]
So I have developed an app in Unity where on selecting a button the VR mode gets enabled (I used some of the code from VrModeController.cs script in the official example) and the user is able to see the VR Environment by rotating the phone around.

I have created 2 scenes 
- UIScene (portrait mode set with `Screen.orientation = ScreenOrientation.Portrait;` and with buttons)
- VRScene (lanscape mode set with `Screen.orientation = ScreenOrientation.LandscapeLeft;` and VR Mode enabled)

On clicking one of the buttons in the UIScene, `VRScene` gets loaded. On tapping the close button, I load UIScene again rather than exiting the app. 

Sometimes the screen looks weird with the VRScene in one half of the screen and the other half is totally black. Like this 👇

![Screenshot_20210722-131240](https://user-images.githubusercontent.com/22871961/126629823-89416d9c-fb38-4f0e-a4a5-3c93d1472265.png)
 
Unity version = 2020.3.0f1
Platform = Android
This happens across various smartphones. Doesn't look like it is device specific issue.

Plus this issue occurs occasionally. I seriously counted and turns out it happens 1 out of 24 times.😅

What is going wrong?

**Comment by Layfully** [comment]
Had this happen multiple times too.

**Comment by sammorris-fss** [comment]
I have this exact same issue, and it's driving me mad! I assume it has something to do with #253, which is apparently fixed in 1.7.0. I've asked for a preview of said fix, since we have no real idea of when 1.7.0 is dropping.

**Comment by sammorris-fss** [comment]
1.7.0 dropped today and appears to have fixed this issue.

**Comment by jballoffet** [comment]
Thanks for reaching out! As @sammorris-fss pointed out, I expect this issue to be solved in v1.7.0 given that a change has been added causing the device params to be reloaded every time the screen size changes (see https://github.com/googlevr/cardboard-xr-plugin/commit/3d41af91480a8fc57eec843f33888cd00e8570f2).

In case the issue still takes place, please reopen this ticket providing a simple repro project and steps required to reproduce the issue. Thanks!

**Comment by knightcube** [comment]
Hey. Thanks! It works fine now. I don't see that half-screen issue anymore. 🎉

**Comment by Layfully** [comment]
Fantastic. Good job!

**Comment by knightcube** [comment]
This is weird but I updated the plugin in my Unity project to `1.7.0` and this bug re-appeared. It happens less often but it still does.

**Comment by sammorris-fss** [comment]
> This is weird but I updated the plugin in my Unity project to `1.7.0` and this bug re-appeared. It happens less often but it still does. Earlier when I tested it was working fine (probably I tested it lesser than required).

Do you have a reliable method to reproduce the issue, or is it just at random?

**Comment by knightcube** [comment]
I tried to figure out some sort of pattern but it indeed seems very random.

**Comment by ti-hardikshah** [comment]
After changing Orientation give 1-2 second wait before initialize that resolve issue too !!

**Comment by MElzallat** [comment]
> After changing Orientation give 1-2 second wait before initialize that resolve issue too !!

1. change rotation
2. wait for 2 seconds
3. initialize XRGeneralSettings

![image](https://user-images.githubusercontent.com/28548609/212764489-86751a55-afba-4ed2-9e0c-e7df7379229f.png)
